### ISSUE TITLE
Unable to create user

### ISSUE THREAD

**Issue by TolotraRam** [devmark/laravel-angular-cms#2]
Hi,

I'm unable to create user from backend, something mess up with roles.

**Comment by whcmark** [comment]
i will fix this bug. i dont test it last night. 
btw this is not release version. so if you need to use it just keep to pull new version

**Comment by whcmark** [comment]
should work now . i will keep update it  

if you get other problems please tell me thanks :)

**Comment by TolotraRam** [comment]
ok

ty, wanna test it :)

Just a question not related, why laravel not lumen if you just use it as a backend api since lumen work great with Angular too and lightweight.

**Comment by whcmark** [comment]
I remember Lumen doesn't support Response macros which i am using. 
I will plan to move to lumen if this project get more stable.

**Comment by TolotraRam** [comment]
Ok, anyway Great works.
