### ISSUE TITLE
Post.category nested set

### ISSUE THREAD

**Issue by TolotraRam** [devmark/laravel-angular-cms#4]
Hi,

I don't know if it's a bug or not implemented yet but nested set is setup on laravel side but not on angular side since i can't create subcategory.

Cheers,

**Comment by whcmark** [comment]
bcz i changed to using lazy loading for category tree list . so category item collapsed automatically. will fix it today

Thanks:)

**Comment by whcmark** [comment]
should work now. please pull new commit

**Comment by TolotraRam** [comment]
Hi,

thanks, works like a charm!!
