### ISSUE TITLE
Feature request : Redirect user to dashboard on unauthorized route.

### ISSUE THREAD

**Issue by TolotraRam** [devmark/laravel-angular-cms#7]

**Comment by whcmark** [comment]
added. i dont test it completely. tell me if any router got error msg.

**Comment by TolotraRam** [comment]
Seem all route is ok but angular is caching last user who has logged in.

I follow these step :
- Created a new role admin who has just permission to access backend
- Created a new user and affected the newly created role (admin)
- Log in as admin@emcoo.com
- Logout
- Login as the new user 
  And then i got the same information as if i'm logged with admin@emcoo.com, need to refresh the browser to get it updated.

I think its ui-router templateCache and how to avoid it ?

**Comment by whcmark** [comment]
Fixed. 

I deep check "Redirect user to dashboard on unauthorized route" now

**Comment by TolotraRam** [comment]
Hi,

Seems cache still remains, on header i always have the name of the last user who has logged in and on dashboard too with permission.

**Comment by whcmark** [comment]
Should work now :relaxed:

**Comment by TolotraRam** [comment]
Thanks, 

It works, wanna test other module now.
